# Generated by Django 6.0 on 2025-12-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
