# Generated by Django 5.2.3 on 2026-03-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_activitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
