# Generated by Django 6.0 on 2025-12-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("projects", "0002_alter_project_description_alter_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="projects",
            field=models.ManyToManyField(
                related_name="users",
                through="projects.ProjectMember",
                to="projects.project",
            ),
        ),
    ]
