# Generated by Django 6.0 on 2025-12-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
        ("projects", "0002_alter_project_description_alter_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_groups", to="projects.project"
            ),
        ),
    ]
