# Generated by Django 5.2.3 on 2026-03-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0004_groupinvite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="groupinvite",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
